'''
A trimming tool to take discord logs generated by DiscordChatExporter (DCE),
then convert them into a format usable for fine tuning LLMs via (Q)LoRA.

Tested with DiscordChatExporter V2.4.0:
https://github.com/Tyrrrz/DiscordChatExporter/releases/tag/2.40

and QLoRA:
https://github.com/artidoro/qlora

This program is designed to read .json files, 
so make sure DCE is exporting in that format.

All other settings in DCE can be left default (although using the "MORE" button 
when exporting and only exporting chat from after when you've joined a given 
server can reduce file size and scraping time signifigantly).
'''
# import the JSON library to read files generated from DCE
import json

